{{-- Courses Panel - Product-style listing for security training courses --}}
<div class="frost-secondary-bg py-5">
    <div class="container courses-container">
        <div class="row mb-5">
            <div class="col-12 text-center">
                <h2 class="text-white">Available Security Courses</h2>
                <h5 class="text-white-50">Professional security training courses designed to help you succeed in the security industry</h5>
            </div>
        </div>

        <div class="row" id="coursesContainer">
            {{-- Courses will be generated by JavaScript --}}
        </div>

        {{-- Call to Action Section --}}
        <div class="row mt-5">
            <div class="col-12 text-center">
                <p class="text-white-50 mb-4">Need help choosing the right course? Our training specialists are here to help.</p>
                <a href="#" class="btn btn-primary btn-lg me-3">Contact Us</a>
                <a href="#" class="btn btn-outline-light btn-lg">View All Courses</a>
            </div>
        </div>
    </div>
</div>

<script>
    // Course data structure - Correct courses and pricing
    const coursesData = [
        {
            id: 1,
            title: "Class D Course - Armed Security License",
            description: "Comprehensive training for armed security professionals with firearms certification. This course covers firearms safety, legal requirements, use of force protocols, and professional responsibilities for armed security officers.",
            price: 299.00,
            duration: "5 Days",
            type: "Armed Security",
            icon: "fas fa-shield-alt",
            features: [
                "Firearms Training & Certification",
                "Legal Requirements & Regulations",
                "Use of Force Protocols",
                "Professional Responsibilities",
                "State Exam Preparation",
                "Certificate Upon Completion"
            ],
            popular: false,
            detailUrl: "/courses/class-d-security",
            enrollUrl: "/enroll/class-d"
        },
        {
            id: 2,
            title: "Class G Course - Unarmed Security License",
            description: "Essential training for unarmed security professionals and private investigators. Learn surveillance techniques, report writing, legal boundaries, and professional conduct standards.",
            price: 199.00,
            duration: "3 Days",
            type: "Unarmed Security",
            icon: "fas fa-user-shield",
            features: [
                "Surveillance Techniques",
                "Professional Report Writing",
                "Legal Boundaries & Ethics",
                "Communication Skills",
                "Emergency Procedures",
                "State Certification"
            ],
            popular: true,
            detailUrl: "/courses/class-g-security",
            enrollUrl: "/enroll/class-g"
        }
    ];

    // Generate course cards
    const coursesContainer = document.getElementById("coursesContainer");

    coursesData.forEach(course => {
        const courseCol = document.createElement('div');
        courseCol.className = 'col-lg-4 col-md-6 col-sm-12 mb-4';

        const popularBadge = course.popular ? `<div class="course-badge popular-badge">Most Popular</div>` : '';
        const featuresList = course.features.map(feature => `<li><i class="fas fa-check text-success me-2"></i>${feature}</li>`).join('');

        courseCol.innerHTML = `
            <div class="course-card h-100">
                <div class="course-header">
                    <div class="course-icon">
                        <i class="${course.icon}"></i>
                    </div>
                    <div class="course-class-badge">${course.id === 1 ? 'CLASS D' : 'CLASS G'}</div>
                    <div class="course-type">${course.type}</div>
                </div>
                <div class="course-body">
                    <h4 class="course-title">${course.title}</h4>
                    <p class="course-description">${course.description}</p>

                    <div class="course-features">
                        <h6>What You'll Learn:</h6>
                        <ul class="feature-list">
                            ${featuresList}
                        </ul>
                    </div>

                    <div class="course-meta">
                        <span class="duration"><i class="fas fa-clock me-2"></i>${course.duration}</span>
                        <span class="course-format"><i class="fas fa-laptop me-2"></i>Online + Live</span>
                    </div>
                </div>
                <div class="course-footer">
                    <div class="course-price">
                        <span class="price">$${course.price.toFixed(2)}</span>
                        <span class="price-note">USD</span>
                    </div>
                    <div class="course-actions">
                        <a href="${course.detailUrl}" class="btn btn-outline-primary btn-sm me-2">Learn More</a>
                        <a href="${course.enrollUrl}" class="btn btn-primary btn-sm">Enroll Now</a>
                    </div>
                </div>
            </div>
        `;        coursesContainer.appendChild(courseCol);
    });
</script>
