<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['country' => 'United States', 'ordering' => 1],
            ['country' => 'Canada', 'ordering' => 2],
            ['country' => 'Afghanistan', 'ordering' => null],
            ['country' => 'Albania', 'ordering' => null],
            ['country' => 'Algeria', 'ordering' => null],
            ['country' => 'Andorra', 'ordering' => null],
            ['country' => 'Angola', 'ordering' => null],
            ['country' => 'Antigua and Barbuda', 'ordering' => null],
            ['country' => 'Argentina', 'ordering' => null],
            ['country' => 'Armenia', 'ordering' => null],
            ['country' => 'Aruba', 'ordering' => null],
            ['country' => 'Australia', 'ordering' => null],
            ['country' => 'Austria', 'ordering' => null],
            ['country' => 'Azerbaijan', 'ordering' => null],
            ['country' => 'Bahamas, The', 'ordering' => null],
            ['country' => 'Bahrain', 'ordering' => null],
            ['country' => 'Bangladesh', 'ordering' => null],
            ['country' => 'Barbados', 'ordering' => null],
            ['country' => 'Belarus', 'ordering' => null],
            ['country' => 'Belgium', 'ordering' => null],
            ['country' => 'Belize', 'ordering' => null],
            ['country' => 'Benin', 'ordering' => null],
            ['country' => 'Bhutan', 'ordering' => null],
            ['country' => 'Bolivia', 'ordering' => null],
            ['country' => 'Bosnia and Herzegovina', 'ordering' => null],
            ['country' => 'Botswana', 'ordering' => null],
            ['country' => 'Brazil', 'ordering' => null],
            ['country' => 'Brunei', 'ordering' => null],
            ['country' => 'Bulgaria', 'ordering' => null],
            ['country' => 'Burkina Faso', 'ordering' => null],
            ['country' => 'Burma', 'ordering' => null],
            ['country' => 'Burundi', 'ordering' => null],
            ['country' => 'Cambodia', 'ordering' => null],
            ['country' => 'Cameroon', 'ordering' => null],
            ['country' => 'Cabo Verde', 'ordering' => null],
            ['country' => 'Central African Republic', 'ordering' => null],
            ['country' => 'Chad', 'ordering' => null],
            ['country' => 'Chile', 'ordering' => null],
            ['country' => 'China', 'ordering' => null],
            ['country' => 'Colombia', 'ordering' => null],
            ['country' => 'Comoros', 'ordering' => null],
            ['country' => 'Congo, Democratic Republic of the', 'ordering' => null],
            ['country' => 'Congo, Republic of the', 'ordering' => null],
            ['country' => 'Costa Rica', 'ordering' => null],
            ['country' => 'Cote d\'Ivoire', 'ordering' => null],
            ['country' => 'Croatia', 'ordering' => null],
            ['country' => 'Cuba', 'ordering' => null],
            ['country' => 'Curacao', 'ordering' => null],
            ['country' => 'Cyprus', 'ordering' => null],
            ['country' => 'Czechia', 'ordering' => null],
            ['country' => 'Denmark', 'ordering' => null],
            ['country' => 'Djibouti', 'ordering' => null],
            ['country' => 'Dominica', 'ordering' => null],
            ['country' => 'Dominican Republic', 'ordering' => null],
            ['country' => 'East Timor', 'ordering' => null],
            ['country' => 'Ecuador', 'ordering' => null],
            ['country' => 'Egypt', 'ordering' => null],
            ['country' => 'El Salvador', 'ordering' => null],
            ['country' => 'Equatorial Guinea', 'ordering' => null],
            ['country' => 'Eritrea', 'ordering' => null],
            ['country' => 'Estonia', 'ordering' => null],
            ['country' => 'Ethiopia', 'ordering' => null],
            ['country' => 'Fiji', 'ordering' => null],
            ['country' => 'Finland', 'ordering' => null],
            ['country' => 'France', 'ordering' => null],
            ['country' => 'Gabon', 'ordering' => null],
            ['country' => 'Gambia, The', 'ordering' => null],
            ['country' => 'Georgia', 'ordering' => null],
            ['country' => 'Germany', 'ordering' => null],
            ['country' => 'Ghana', 'ordering' => null],
            ['country' => 'Greece', 'ordering' => null],
            ['country' => 'Grenada', 'ordering' => null],
            ['country' => 'Guatemala', 'ordering' => null],
            ['country' => 'Guinea', 'ordering' => null],
            ['country' => 'Guinea-Bissau', 'ordering' => null],
            ['country' => 'Guyana', 'ordering' => null],
            ['country' => 'Haiti', 'ordering' => null],
            ['country' => 'Holy See', 'ordering' => null],
            ['country' => 'Honduras', 'ordering' => null],
            ['country' => 'Hong Kong', 'ordering' => null],
            ['country' => 'Hungary', 'ordering' => null],
            ['country' => 'Iceland', 'ordering' => null],
            ['country' => 'India', 'ordering' => null],
            ['country' => 'Indonesia', 'ordering' => null],
            ['country' => 'Iran', 'ordering' => null],
            ['country' => 'Iraq', 'ordering' => null],
            ['country' => 'Ireland', 'ordering' => null],
            ['country' => 'Israel', 'ordering' => null],
            ['country' => 'Italy', 'ordering' => null],
            ['country' => 'Jamaica', 'ordering' => null],
            ['country' => 'Japan', 'ordering' => null],
            ['country' => 'Jordan', 'ordering' => null],
            ['country' => 'Kazakhstan', 'ordering' => null],
            ['country' => 'Kenya', 'ordering' => null],
            ['country' => 'Kiribati', 'ordering' => null],
            ['country' => 'Korea, North', 'ordering' => null],
            ['country' => 'Korea, South', 'ordering' => null],
            ['country' => 'Kosovo', 'ordering' => null],
            ['country' => 'Kuwait', 'ordering' => null],
            ['country' => 'Kyrgyzstan', 'ordering' => null],
            ['country' => 'Laos', 'ordering' => null],
            ['country' => 'Latvia', 'ordering' => null],
            ['country' => 'Lebanon', 'ordering' => null],
            ['country' => 'Lesotho', 'ordering' => null],
            ['country' => 'Liberia', 'ordering' => null],
            ['country' => 'Libya', 'ordering' => null],
            ['country' => 'Liechtenstein', 'ordering' => null],
            ['country' => 'Lithuania', 'ordering' => null],
            ['country' => 'Luxembourg', 'ordering' => null],
            ['country' => 'Macau', 'ordering' => null],
            ['country' => 'Macedonia', 'ordering' => null],
            ['country' => 'Madagascar', 'ordering' => null],
            ['country' => 'Malawi', 'ordering' => null],
            ['country' => 'Malaysia', 'ordering' => null],
            ['country' => 'Maldives', 'ordering' => null],
            ['country' => 'Mali', 'ordering' => null],
            ['country' => 'Malta', 'ordering' => null],
            ['country' => 'Marshall Islands', 'ordering' => null],
            ['country' => 'Mauritania', 'ordering' => null],
            ['country' => 'Mauritius', 'ordering' => null],
            ['country' => 'Mexico', 'ordering' => null],
            ['country' => 'Micronesia', 'ordering' => null],
            ['country' => 'Moldova', 'ordering' => null],
            ['country' => 'Monaco', 'ordering' => null],
            ['country' => 'Mongolia', 'ordering' => null],
            ['country' => 'Montenegro', 'ordering' => null],
            ['country' => 'Morocco', 'ordering' => null],
            ['country' => 'Mozambique', 'ordering' => null],
            ['country' => 'Namibia', 'ordering' => null],
            ['country' => 'Nauru', 'ordering' => null],
            ['country' => 'Nepal', 'ordering' => null],
            ['country' => 'Netherlands', 'ordering' => null],
            ['country' => 'New Zealand', 'ordering' => null],
            ['country' => 'Nicaragua', 'ordering' => null],
            ['country' => 'Niger', 'ordering' => null],
            ['country' => 'Nigeria', 'ordering' => null],
            ['country' => 'North Korea', 'ordering' => null],
            ['country' => 'Norway', 'ordering' => null],
            ['country' => 'Oman', 'ordering' => null],
            ['country' => 'Pakistan', 'ordering' => null],
            ['country' => 'Palau', 'ordering' => null],
            ['country' => 'Palestinian Territories', 'ordering' => null],
            ['country' => 'Panama', 'ordering' => null],
            ['country' => 'Papua New Guinea', 'ordering' => null],
            ['country' => 'Paraguay', 'ordering' => null],
            ['country' => 'Peru', 'ordering' => null],
            ['country' => 'Philippines', 'ordering' => null],
            ['country' => 'Poland', 'ordering' => null],
            ['country' => 'Portugal', 'ordering' => null],
            ['country' => 'Qatar', 'ordering' => null],
            ['country' => 'Romania', 'ordering' => null],
            ['country' => 'Russia', 'ordering' => null],
            ['country' => 'Rwanda', 'ordering' => null],
            ['country' => 'Saint Kitts and Nevis', 'ordering' => null],
            ['country' => 'Saint Lucia', 'ordering' => null],
            ['country' => 'Saint Vincent and the Grenadines', 'ordering' => null],
            ['country' => 'Samoa', 'ordering' => null],
            ['country' => 'San Marino', 'ordering' => null],
            ['country' => 'Sao Tome and Principe', 'ordering' => null],
            ['country' => 'Saudi Arabia', 'ordering' => null],
            ['country' => 'Senegal', 'ordering' => null],
            ['country' => 'Serbia', 'ordering' => null],
            ['country' => 'Seychelles', 'ordering' => null],
            ['country' => 'Sierra Leone', 'ordering' => null],
            ['country' => 'Singapore', 'ordering' => null],
            ['country' => 'Sint Maarten', 'ordering' => null],
            ['country' => 'Slovakia', 'ordering' => null],
            ['country' => 'Slovenia', 'ordering' => null],
            ['country' => 'Solomon Islands', 'ordering' => null],
            ['country' => 'Somalia', 'ordering' => null],
            ['country' => 'South Africa', 'ordering' => null],
            ['country' => 'South Korea', 'ordering' => null],
            ['country' => 'South Sudan', 'ordering' => null],
            ['country' => 'Spain', 'ordering' => null],
            ['country' => 'Sri Lanka', 'ordering' => null],
            ['country' => 'Sudan', 'ordering' => null],
            ['country' => 'Suriname', 'ordering' => null],
            ['country' => 'Swaziland', 'ordering' => null],
            ['country' => 'Sweden', 'ordering' => null],
            ['country' => 'Switzerland', 'ordering' => null],
            ['country' => 'Syria', 'ordering' => null],
            ['country' => 'Taiwan', 'ordering' => null],
            ['country' => 'Tajikistan', 'ordering' => null],
            ['country' => 'Tanzania', 'ordering' => null],
            ['country' => 'Thailand', 'ordering' => null],
            ['country' => 'Timor-Leste', 'ordering' => null],
            ['country' => 'Togo', 'ordering' => null],
            ['country' => 'Tonga', 'ordering' => null],
            ['country' => 'Trinidad and Tobago', 'ordering' => null],
            ['country' => 'Tunisia', 'ordering' => null],
            ['country' => 'Turkey', 'ordering' => null],
            ['country' => 'Turkmenistan', 'ordering' => null],
            ['country' => 'Tuvalu', 'ordering' => null],
            ['country' => 'Uganda', 'ordering' => null],
            ['country' => 'Ukraine', 'ordering' => null],
            ['country' => 'United Arab Emirates', 'ordering' => null],
            ['country' => 'United Kingdom', 'ordering' => null],
            ['country' => 'Uruguay', 'ordering' => null],
            ['country' => 'Uzbekistan', 'ordering' => null],
            ['country' => 'Vanuatu', 'ordering' => null],
            ['country' => 'Venezuela', 'ordering' => null],
            ['country' => 'Vietnam', 'ordering' => null],
            ['country' => 'Yemen', 'ordering' => null],
            ['country' => 'Zambia', 'ordering' => null],
            ['country' => 'Zimbabwe', 'ordering' => null],
        ];

        DB::table('countries')->insert($countries);
    }
}
