<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ExamQuestionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $examQuestions = [
            ['id' => 1, 'lesson_id' => 1, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'The Legislature recognizes that each individual licensed by the Department must be at least 18 years of age and be of good moral character.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 2, 'lesson_id' => 1, 'eq_spec_id' => null, 'correct' => 3, 'question' => 'A Florida "D" licensed Security Officer, may work armed if required by their duty and post, provided that they also have:', 'answer_1' => 'Carry Concealed Weapons Permit', 'answer_2' => 'A Florida "K" License', 'answer_3' => 'A Florida "G" License', 'answer_4' => 'None of the Above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 3, 'lesson_id' => 1, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'The concealed weapon or firearm program is controlled and regulated by the Florida Department of Agriculture and Consumer Services, Division of Licensing Department.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 4, 'lesson_id' => 1, 'eq_spec_id' => null, 'correct' => 3, 'question' => 'A Class "DI" License is a __ License?', 'answer_1' => 'Security Officer', 'answer_2' => 'Private Investigator', 'answer_3' => 'Security Officer Instructor', 'answer_4' => 'Drill Sergeant Instructor', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 5, 'lesson_id' => 1, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'Any Security Agency or Licensee can use the Great Seal of the State of Florida.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 6, 'lesson_id' => 1, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'Class "D" Licensees shall perform duties regulated under Chapter 493 in a uniform which bears at least:', 'answer_1' => 'At least one patch or emblem with the name of the Security Agency clearly visible.', 'answer_2' => 'A hat', 'answer_3' => 'A badge', 'answer_4' => 'A five-pointed star', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 7, 'lesson_id' => 1, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'Individual Licenses and Agency Identification Card must be in the possession of the Security Officer at all times while they are on duty.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 8, 'lesson_id' => 1, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'A "D" License expires after __ years?', 'answer_1' => '1', 'answer_2' => '2', 'answer_3' => '5', 'answer_4' => '10', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 9, 'lesson_id' => 1, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'An "assault" is an intentional, unlawful threat by word or act to do violence to a person or another.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 10, 'lesson_id' => 1, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'The offense of "battery" occurs when a person:', 'answer_1' => 'Actually, and intentionally touching/striking another person against their will.', 'answer_2' => 'Uses a deadly weapon', 'answer_3' => 'Accuses him or her of a crime', 'answer_4' => 'Verbally threatens another person', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 11, 'lesson_id' => 1, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'Misdemeanors are minor crimes punishable by a year of less in jail.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 12, 'lesson_id' => 1, 'eq_spec_id' => null, 'correct' => 1, 'question' => '__ are significant crimes punishable by a year or more in prison.', 'answer_1' => 'Felonies', 'answer_2' => 'Misdemeanors', 'answer_3' => 'Crimes', 'answer_4' => 'Traffic Tickets', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 13, 'lesson_id' => 1, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'Florida Statute Chapter 776 covers Justifiable Use of Force.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 14, 'lesson_id' => 1, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'The definition of Forcible Felonies under Florida Statute 776.08 means treason, murder, sexual battery, home invasion robbery or any other felony which involves the use or threat of physical force or violence against any individual.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 15, 'lesson_id' => 1, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'If you are the witness to a crime you may have to:', 'answer_1' => 'Remain calm but be as alert and observant as possible.', 'answer_2' => 'Make as many mental notes as possible to help identify the suspect.', 'answer_3' => 'Report the crime immediately and stay close by until authorities arrive.', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 16, 'lesson_id' => 1, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'The term "Deadly Force" means:', 'answer_1' => 'Allow no one in except the authorities.', 'answer_2' => 'Force that is likely to cause death or great bodily harm', 'answer_3' => 'Using force in detaining someone', 'answer_4' => 'Slap across the face', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 17, 'lesson_id' => 1, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'When is the use of force justified?', 'answer_1' => 'You or a third person are in imminent danger of being harmed', 'answer_2' => 'When you are verbally threatened with words', 'answer_3' => 'When someone calls you a rent-a-cop', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 18, 'lesson_id' => 1, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'A Florida "D" Licensed Security Officer has the same powers of arrest as a Sworn Law Enforcement Officer.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 19, 'lesson_id' => 1, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'Which of the following is not a disciplinary action the DOL can impose under 5N-1.113?', 'answer_1' => 'Failure to notify the DOL of a Security Officers change of address within 10 days of such a change.', 'answer_2' => 'Failure of a Security Officer to carry their individual "D" License on duty', 'answer_3' => 'Violation of a Cease and Desist order issued by the DOL', 'answer_4' => 'Wearing a uniform with the shirt untucked and ketchup stains on the front', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 20, 'lesson_id' => 1, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'In a criminal case; guilt requires proof beyond a reasonable doubt and the burden of proof is on the State.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 21, 'lesson_id' => 1, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'After a crime or accident, you should write an accurate and detailed:', 'answer_1' => 'Incident Report', 'answer_2' => 'Weather Report', 'answer_3' => 'Vehicle Report', 'answer_4' => 'Parking Violation Report', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 22, 'lesson_id' => 1, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'As a Security Officer at a Crime/Accident Scene, you may prohibit bystanders standing on public property from taking pictures or video on their cell phones.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 23, 'lesson_id' => 1, 'eq_spec_id' => null, 'correct' => 3, 'question' => 'A __ is a group of citizens who hears the testimony in legal disputes and determines what they believe to be the truth.', 'answer_1' => 'Judge', 'answer_2' => 'Prosecutor', 'answer_3' => 'Jury', 'answer_4' => 'Lawyer', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 24, 'lesson_id' => 1, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'A written command to a person to testify before a court or be punished is known as a __.', 'answer_1' => 'Warrant', 'answer_2' => 'Subpoena', 'answer_3' => 'Letter', 'answer_4' => 'Deposition', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 25, 'lesson_id' => 1, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'A Security Officer can be used as a witness in court.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 26, 'lesson_id' => 1, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'It is a 3rd degree felony to knowingly possess, issue, cause to be issued, sell, submit, or offer a fraudulent training certificate, proficiency form, or other official document that declares an applicant to have successfully completed any course of training required for licensure under Chapter 493 when that person either knew or should have known that the certificate, form, or document was fraudulent.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
        ];

        // Insert first batch of questions (1-26)
        foreach ($examQuestions as $question) {
            DB::table('exam_questions')->insert($question);
        }

        // Additional questions batch 2 (27-52)
        $examQuestions2 = [
            ['id' => 27, 'lesson_id' => 2, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'Your primary function as an Unarmed Security Officer is to Observe and Report.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 28, 'lesson_id' => 2, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'What are some of the types of risk that Security Officers need to be aware of?', 'answer_1' => 'Fire and Fire Hazards', 'answer_2' => 'Trespassing', 'answer_3' => 'Robbery', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 29, 'lesson_id' => 2, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'There are generally four primary causes of loss of product in the retail world; Internal Theft, External Theft, Operational Errors and Vendor Theft.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 30, 'lesson_id' => 2, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'Indicators of Internal Theft are:', 'answer_1' => 'Merchandise thrown in the trash to be retrieved later', 'answer_2' => 'Suspicious vehicles parked near the back door or dumpster', 'answer_3' => 'Employee purposely trying to work unsupervised', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 31, 'lesson_id' => 2, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'One way to protect high value items, such as jewelry, computers, cell phones, etc. is to keep them behind the counter or in a glass case.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 32, 'lesson_id' => 2, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'What are some different types of Security Employment?', 'answer_1' => 'Government Facilities - Courts, VA Hospital, Social Security Office', 'answer_2' => 'Cultural Properties - Museums, Aquariums, Zoos', 'answer_3' => 'Commercial Real Estate - Shopping Malls, Department Stores', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 33, 'lesson_id' => 2, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'Shoplifters do not like to be recognized and they will look for out-of-the-way areas to try and conceal merchandise.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 34, 'lesson_id' => 2, 'eq_spec_id' => null, 'correct' => 1, 'question' => '__ is the knowledge and attitude members of an organization possess regarding the protection of the physical, informational and assets of an organization.', 'answer_1' => 'Security Awareness', 'answer_2' => 'Trespassing', 'answer_3' => 'First Aid', 'answer_4' => 'Workplace Violence', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 35, 'lesson_id' => 2, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'What are some Elements of Theft?', 'answer_1' => 'Intent to deprive permanently', 'answer_2' => 'Carrying away or moving of property', 'answer_3' => 'Wrongful taking of property of another', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 36, 'lesson_id' => 3, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'When on the radio do not:', 'answer_1' => 'Use profanity', 'answer_2' => 'Yell', 'answer_3' => 'Argue', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 37, 'lesson_id' => 3, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'Problems with two-way radios are:', 'answer_1' => 'Short battery life', 'answer_2' => 'Provides instant communication', 'answer_3' => 'Can communicate with many officers at the same time', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 38, 'lesson_id' => 3, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'You should eat, chew gum, and talk on the official company telephone.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 39, 'lesson_id' => 3, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'To be heard on the radio you must speak clearly with the radio at least 2 inches from your mouth.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 40, 'lesson_id' => 4, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'Security Officers are public figures. Their appearance and behavior must be professional.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 41, 'lesson_id' => 4, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'As a Security Officer, you should be which of the following?', 'answer_1' => 'Dependable and Punctual', 'answer_2' => 'Trustworthy and Loyal', 'answer_3' => 'Honest and Fair', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 42, 'lesson_id' => 4, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'Security Officers conduct, is closely observed by:', 'answer_1' => 'The Public', 'answer_2' => 'Employees', 'answer_3' => 'Fellow Officers', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 43, 'lesson_id' => 4, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'Sexual Harassment can be defined as unwelcome sexual advances, requests for sexual favors, or other verbal or physical conduct of a sexual nature.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 44, 'lesson_id' => 4, 'eq_spec_id' => null, 'correct' => 3, 'question' => 'Which of these is not a characteristic of effective assertiveness?', 'answer_1' => 'Calm controlled facial expressions', 'answer_2' => 'Confidence', 'answer_3' => 'Idle threats', 'answer_4' => 'Strong Command Voice', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 45, 'lesson_id' => 4, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'Wearing excessive amounts of jewelry while on duty is acceptable?', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 46, 'lesson_id' => 4, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'Security Officers may take advantage during work hours to surf the internet, talk on their cell phones and send text messages?', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 47, 'lesson_id' => 4, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'Good Public Relations start with?', 'answer_1' => 'Being strict', 'answer_2' => 'Your appearance', 'answer_3' => 'Angry Face', 'answer_4' => 'Yelling', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 48, 'lesson_id' => 4, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'Public Relations consist of a __ understanding between an organization and its visitors, customers, and / or clients?', 'answer_1' => 'Mutual', 'answer_2' => 'Annoying', 'answer_3' => 'Dictating', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 49, 'lesson_id' => 4, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'Common courtesy is:', 'answer_1' => 'Saying Thank you, You\'re Welcome, May I Help You?', 'answer_2' => 'Arguing with customers', 'answer_3' => 'Doing whatever you want', 'answer_4' => 'Ignoring your Post Orders', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 50, 'lesson_id' => 4, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'The key words in Public Relations are "__" need "__"?', 'answer_1' => 'Mutual / Satisfaction', 'answer_2' => 'Security / Raise', 'answer_3' => 'I / break', 'answer_4' => 'None of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 51, 'lesson_id' => 4, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'If a Security Officer is asked to give a statement by a media representative, they can respond "off the record."', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 52, 'lesson_id' => 4, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'The Security Officer is frequently the first point of contact with the public?', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
        ];

        foreach ($examQuestions2 as $question) {
            DB::table('exam_questions')->insert($question);
        }

        // Additional questions batch 3 (53-100) - Lesson 5-11
        $examQuestions3 = [
            ['id' => 53, 'lesson_id' => 5, 'eq_spec_id' => null, 'correct' => 3, 'question' => 'What is the process of observation?', 'answer_1' => 'Night, Day, Twilight', 'answer_2' => 'Smell, Taste, Hearing', 'answer_3' => 'Noticing, Interpreting, Recalling', 'answer_4' => 'Looking, Touching, Smelling', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 54, 'lesson_id' => 5, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'You can improve your memory by practicing these skills:', 'answer_1' => 'Running, Lifting, Swimming', 'answer_2' => 'Concentration, Association, Repetition', 'answer_3' => 'Soap, Rinse, Lather', 'answer_4' => 'Looking, Hearing, Smelling', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 55, 'lesson_id' => 5, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'Identify the five senses:', 'answer_1' => 'Sight, Hearing, Smell, Touch and Taste', 'answer_2' => 'Look, Listen, Sniff, Grab, Lick', 'answer_3' => 'Pop, Lock, Drop, Stop, Think', 'answer_4' => 'None of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 56, 'lesson_id' => 5, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'The visibility of an object depends on what three things?', 'answer_1' => 'Hot, Cold, Warm', 'answer_2' => 'Distance, Size, Illumination', 'answer_3' => 'Sounds, Radar, Noise', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 57, 'lesson_id' => 5, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'Combining your prior learning and knowledge of security work, experience and common sense will make for a better security report.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 58, 'lesson_id' => 5, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'Security Incident Reports must be clear, accurate, concise and __.', 'answer_1' => 'Blurry', 'answer_2' => 'Completed prior to the end of your shift', 'answer_3' => 'Unclear', 'answer_4' => 'Sloppy', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 59, 'lesson_id' => 5, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'You should collect the following at an incident scene:', 'answer_1' => 'Witness names and address', 'answer_2' => 'Witness contact information such as phone number, email, etc.', 'answer_3' => 'Name and Badge number of highest ranking responding Law Enforcement Officer', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 60, 'lesson_id' => 5, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'A Security Officers notes may be defined simply as "a quick and accurate method of recording what you saw, and your actions taken"', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 61, 'lesson_id' => 5, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'All Security Reports should contain answers to the best of your ability to the following questions: who, what, when, why, where and how?', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 62, 'lesson_id' => 5, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'The report should be organized for', 'answer_1' => 'Your supervisor', 'answer_2' => 'The client', 'answer_3' => 'Law enforcement', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 63, 'lesson_id' => 5, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'When observing a suspect, you should remember:', 'answer_1' => 'Height and weight', 'answer_2' => 'Race, age, gender', 'answer_3' => 'Description of clothing or distinguishing marks', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 64, 'lesson_id' => 5, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'A Security Officer has a "License to Stare".', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 65, 'lesson_id' => 5, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'A Vehicle Log should include the accurate time of arrival and time of departure.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 66, 'lesson_id' => 5, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'A Daily Activity Report (DAR) should include: date, time, specific location, activity performed, all observations, actions taken by the Officer, and the results of those actions taken.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 67, 'lesson_id' => 5, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'When considering a persons description, what are the things people can change quickly?', 'answer_1' => 'Hair, clothing, jewelry', 'answer_2' => 'Age', 'answer_3' => 'Height', 'answer_4' => 'Weight', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 68, 'lesson_id' => 5, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'As a Security Professional practicing Situational Awareness you should be constantly be alert for suspicious:', 'answer_1' => 'Vehicles', 'answer_2' => 'People', 'answer_3' => 'Circumstances', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 69, 'lesson_id' => 5, 'eq_spec_id' => null, 'correct' => 3, 'question' => 'As it pertains to the five senses, a Professional Security Officer should be aware that not all types of smoke or gas can be detected by the sense of smell. Which of the following toxic materials cannot be detected by our sense of smell:', 'answer_1' => 'Rotting Food', 'answer_2' => 'Gasoline', 'answer_3' => 'Carbon monoxide', 'answer_4' => 'Smoke from a wood fire', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 70, 'lesson_id' => 8, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'What are the "perception factors" when communicating with others?', 'answer_1' => 'Appearance', 'answer_2' => 'Body language', 'answer_3' => 'Tone of voice', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 71, 'lesson_id' => 8, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'How well you communicate __ and __ will reflect on you as a professional Security Officer?', 'answer_1' => 'verbally / in writing', 'answer_2' => 'up / down', 'answer_3' => 'emotions / feelings', 'answer_4' => 'None of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 72, 'lesson_id' => 8, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'Which of the following can be considered offensive body language?', 'answer_1' => 'Pointing your finger at someone aggressively', 'answer_2' => 'Placing your hands at chest or waist level in a non-threading manner', 'answer_3' => 'Using a proper interview stance', 'answer_4' => 'None of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 73, 'lesson_id' => 8, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'A Security Officer is a figure of authority and must always maintain a professional demeanor and attitude.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 74, 'lesson_id' => 8, 'eq_spec_id' => null, 'correct' => 3, 'question' => 'When dealing with an angry individual, you should never argue or fight back with them, just attempt to __ the situation.', 'answer_1' => 'Escalate', 'answer_2' => 'Stop', 'answer_3' => 'De-escalate', 'answer_4' => 'None of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 75, 'lesson_id' => 8, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'A Security Officers appearance plays a significant role in setting the tone for when they are in contact with the public.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 76, 'lesson_id' => 8, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'When dealing with a difficult individual, the professional security officer should:', 'answer_1' => 'Remain calm', 'answer_2' => 'Act appropriately', 'answer_3' => 'Be objective', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 77, 'lesson_id' => 8, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'An Officer\'s tone of voice and demeanor can either escalate a situation or keep a situation under control.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 78, 'lesson_id' => 8, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'A Security Officer must maintain a greater reactionary distance when dealing with personnel who are emotionally upset, angry or under the influence of drugs / alcohol, etc.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 79, 'lesson_id' => 6, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'Mobile Patrols cover:', 'answer_1' => 'Streets', 'answer_2' => 'Sidewalks', 'answer_3' => 'Parking lots', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 80, 'lesson_id' => 6, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'This measure is to prevent security patrols from becoming routine and predictable:', 'answer_1' => 'Vary the route and vary the time you go on patrol', 'answer_2' => 'Patrolling at the same time every day', 'answer_3' => 'Drive in reverse', 'answer_4' => 'Take extra-long breaks at the gate house', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 81, 'lesson_id' => 6, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'While walking, standing, sitting, or parking, and listening quietly, a Security Officer may better hear things happening that affect the persons or property he or she has been hired to protect.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 82, 'lesson_id' => 6, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'While on patrol you should do which of the following:', 'answer_1' => 'Conduct a radio check periodically with command center or dispatch', 'answer_2' => 'Avoid distractions, be observant', 'answer_3' => 'Use your field notes, later, write accurate reports', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 83, 'lesson_id' => 7, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'The purpose of an interview is:', 'answer_1' => 'To obtain information', 'answer_2' => 'To argue', 'answer_3' => 'To yell and scream', 'answer_4' => 'To have a staring contest', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 84, 'lesson_id' => 7, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'Identify the three interviewing styles:', 'answer_1' => 'Low, Medium, High', 'answer_2' => 'Direct, Indirect, Sympathetic', 'answer_3' => 'Straight, Roundabout, Out of Bounds', 'answer_4' => 'Average, Old, Young', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 85, 'lesson_id' => 7, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'An interview should take place in a one on one situation.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 86, 'lesson_id' => 7, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'A person has the right to __ answering questions at any time.', 'answer_1' => 'Refuse', 'answer_2' => 'Talk', 'answer_3' => 'Complain about', 'answer_4' => 'Take a break before', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 87, 'lesson_id' => 9, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'If you find a bomb:', 'answer_1' => 'Move closer to touch and inspect it to make sure it is real.', 'answer_2' => 'Do not touch it, notify the authorities, stay off your radio and keep everyone at a safe distance.', 'answer_3' => 'Yell and scream "bomb" at the top of your lungs', 'answer_4' => 'Just run and save yourself', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 88, 'lesson_id' => 9, 'eq_spec_id' => null, 'correct' => 3, 'question' => '__ are not examples of natural emergencies', 'answer_1' => 'Lightning strikes', 'answer_2' => 'Floods', 'answer_3' => 'Riots', 'answer_4' => 'Hurricanes', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 89, 'lesson_id' => 9, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'In preparation for an emergency, you should know the:', 'answer_1' => 'Emergency Action Plan', 'answer_2' => 'Emergency Evacuation Plan', 'answer_3' => 'Location of all Fire Exits', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 90, 'lesson_id' => 9, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'You should not take a bomb threat seriously.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 91, 'lesson_id' => 9, 'eq_spec_id' => 1, 'correct' => 1, 'question' => 'Before hurricane season starts (June 1 to November 30) you should begin planning for the safety of your post. What is the first step that should be taken?', 'answer_1' => 'Become familiar with the Hurricane Preparedness Plan. Ensure to follow the checklist and inspect all items well before hurricane season starts.', 'answer_2' => 'Go on vacation', 'answer_3' => 'Check the no parking lines', 'answer_4' => 'Ask for a raise', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 92, 'lesson_id' => 9, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'Evacuation from a site may be necessary as a result of fire, explosion, chemical leak, structural fault or equipment failure.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 93, 'lesson_id' => 10, 'eq_spec_id' => null, 'correct' => 3, 'question' => 'Oxygen, fuel and heat are:', 'answer_1' => 'Ingredients of a drink', 'answer_2' => 'Ingredients of a soup', 'answer_3' => 'Ingredients of a fire', 'answer_4' => 'Ingredients of a cake', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 94, 'lesson_id' => 10, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'There are five (5) classes of fire. A, B, C, D and K', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 95, 'lesson_id' => 10, 'eq_spec_id' => null, 'correct' => 3, 'question' => 'The acronym used to remember how to use a fire extinguisher is:', 'answer_1' => 'OPORD', 'answer_2' => 'KFC', 'answer_3' => 'PASS (Pull, Aim, Squeeze, Sweep)', 'answer_4' => 'LCPL', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 96, 'lesson_id' => 10, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'In a fire situation you should sound the alarm, rescue any person(s) in immediate danger, and follow emergency procedures.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 97, 'lesson_id' => 10, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'In case of fire:', 'answer_1' => 'Use elevators', 'answer_2' => 'Call 911, tell them the location of the fire, assist in evacuation', 'answer_3' => 'Open all doors', 'answer_4' => 'Run up to the roof', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 98, 'lesson_id' => 10, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'You should know the evacuation plan in case of an emergency.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 99, 'lesson_id' => 10, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'Flammable liquids, gasoline, oil and grease make __ fires.', 'answer_1' => 'Class A', 'answer_2' => 'Class B', 'answer_3' => 'Class C', 'answer_4' => 'Class D', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 100, 'lesson_id' => 10, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'OSHA stands for:', 'answer_1' => 'Occupational Safety and Health Administration', 'answer_2' => 'Organization of Support and Hungry Americans', 'answer_3' => 'Department of Transportation', 'answer_4' => 'Operational Situation of Hospitals and Alumni', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
        ];

        foreach ($examQuestions3 as $question) {
            DB::table('exam_questions')->insert($question);
        }

        // Additional questions batch 4 (101-160) - Fire Safety, First Aid, and Information Security
        $examQuestions4 = [
            ['id' => 101, 'lesson_id' => 10, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'A Security Officer must know what emergency equipment is at their post, where it is located, how to access it and how to use it.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 102, 'lesson_id' => 10, 'eq_spec_id' => 1, 'correct' => 1, 'question' => 'Florida Statute 877.15 makes it a second-degree misdemeanor to fail to control or report a dangerous fire.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 103, 'lesson_id' => 10, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'During an emergency, the security officer should:', 'answer_1' => 'Advise first responders of any personnel still inside, if known.', 'answer_2' => 'Provide assistance and follow directions of first responders', 'answer_3' => 'Be prepared to conduct traffic control to assist emergency vehicles at your site', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 104, 'lesson_id' => 11, 'eq_spec_id' => null, 'correct' => 3, 'question' => 'The Steps to follow in a Medical Emergency are:', 'answer_1' => 'Get in your vehicle, go to lunch, come back when it is over', 'answer_2' => 'Check Facebook, go on break, leave for the day', 'answer_3' => 'Check the scene and the victim, Call 911, Care for the injured', 'answer_4' => 'Move, Shoot, Communicate', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 105, 'lesson_id' => 11, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'When should you call 911?', 'answer_1' => 'The person has the sniffles', 'answer_2' => 'The person has a paper cut', 'answer_3' => 'The person has stubbed their toe', 'answer_4' => 'The person states they are having difficulty breathing or chest pains', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 106, 'lesson_id' => 11, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'When performing CPR, you should do compressions at a rate of __ compressions per minute:', 'answer_1' => '5 to 10', 'answer_2' => '15 to 30', 'answer_3' => '40 to 60', 'answer_4' => '100 to 120', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 107, 'lesson_id' => 11, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'AED stands for Automated External Defibrillator.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 108, 'lesson_id' => 11, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'The three categories of bleeding are:', 'answer_1' => 'Running, Gushing, Trickling', 'answer_2' => 'Capillary, Venous, Arterial', 'answer_3' => 'Voided, Emptied, Suctioned', 'answer_4' => 'One, Two, Three', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 109, 'lesson_id' => 11, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'If you see someone who appears to be choking on an object, you should:', 'answer_1' => 'Confirm they are choking by asking them if they are choking', 'answer_2' => 'Call 911 or direct someone to call 911 immediately', 'answer_3' => 'Administer Back Blows and Abdominal Thrusts', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 110, 'lesson_id' => 11, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'Shock is a serious condition that occurs when the cardiovascular system is unable to supply enough blood flow to the body.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 111, 'lesson_id' => 11, 'eq_spec_id' => 1, 'correct' => 1, 'question' => 'What is the Florida Good Samaritan Act under Chapter 768.13?', 'answer_1' => 'Any person who in good faith, renders emergency care is protected from civil liability', 'answer_2' => 'A person who tells the victim they don\'t look too good', 'answer_3' => 'Someone who takes a lot of pictures and video', 'answer_4' => 'Someone who helps keep the park clean', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 112, 'lesson_id' => 11, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'If you have been exposed to a victim\'s bodily fluids while you are performing first aid, you should inform medical personnel immediately', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 113, 'lesson_id' => 11, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'When there is no Personal Protective Equipment available, Hands only CPR is perfectly acceptable.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 114, 'lesson_id' => 11, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'If someone has swallowed or inhaled a poison, you should', 'answer_1' => 'Call 911', 'answer_2' => 'Try and identify what they swallowed or inhaled and the amount', 'answer_3' => 'Do NOT induce vomiting', 'answer_4' => 'All of the Above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 115, 'lesson_id' => 11, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'When describing the symptoms of a stroke the acronym FAST stands for:', 'answer_1' => 'Face (Facial Drooping), Arm (Arm Weakness), Speech (Slurred Speech), Time (Time to call 911)', 'answer_2' => 'Fumble, Alarm, Speed, Tissue', 'answer_3' => 'Fortune, Allies, Simple, Tonight', 'answer_4' => 'None of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 116, 'lesson_id' => 11, 'eq_spec_id' => null, 'correct' => 3, 'question' => 'When the AED arrives, what is the first step for using it?', 'answer_1' => 'Apply the pads to the victim\'s chest', 'answer_2' => 'Clear the patient', 'answer_3' => 'Turn the AED on', 'answer_4' => 'Press the shock button', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 117, 'lesson_id' => 11, 'eq_spec_id' => null, 'correct' => 3, 'question' => 'What should you do if you need to use an AED on someone who has been submerged in water?', 'answer_1' => 'Do not move the victim', 'answer_2' => 'Do not use the AED', 'answer_3' => 'Pull the victim out of the water, remove the wet shirt (if present) and dry the chest as best as you can with whatever you can use. Place the AED pads only after removing as much moisture as possible.', 'answer_4' => 'Do not pull the victim out of the water but wipe the chest before placing the pads.', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 118, 'lesson_id' => 11, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'While performing high-quality CPR on an adult, what action should you ensure is being accomplished?', 'answer_1' => 'Maintaining a compression rate of 10 per minute', 'answer_2' => 'Placing hands on the abdomen', 'answer_3' => 'Place hands on the victims back', 'answer_4' => 'Compressing to a depth of at least 2 inches at 100-120 compressions per minute', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 119, 'lesson_id' => 11, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'Why is allowing complete chest recoil important when performing high-quality CPR?', 'answer_1' => 'The heart will adequately refill between compressions', 'answer_2' => 'There will be a reduction of rescuer fatigue', 'answer_3' => 'The rate of chest compressions will increase', 'answer_4' => 'It will reduce the risk of rib fractures', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 120, 'lesson_id' => 11, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'When treating a heat casualty, Heat stroke is considered a medical emergency.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 121, 'lesson_id' => 11, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'If a person is injured and a sharp object, such as a nail or a knife, remains partly stuck in the body, leave it in the body. Taking it out may cause more damage.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 122, 'lesson_id' => 11, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'When properly placing a tourniquet, place the tourniquet 2-4 inches above the location of the injured limb.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 123, 'lesson_id' => 12, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'The integrity of information means:', 'answer_1' => 'Ensuring that your information remains confidential and only those who should access that information can do so', 'answer_2' => 'Knowing that nobody has been able to change your information so you can depend on its accuracy', 'answer_3' => 'Making sure that your information is available when you need it by making backup copies', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 124, 'lesson_id' => 12, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'Everyone who uses a computer, smartphone or other mobile device needs to understand how to keep your data secure.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 125, 'lesson_id' => 12, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'Since Security Officers are not health care workers, they are exempt from the need to protect patient information.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 126, 'lesson_id' => 12, 'eq_spec_id' => null, 'correct' => 3, 'question' => 'HIPAA stands for:', 'answer_1' => 'Hopeful Is Potentially An Advertisement', 'answer_2' => 'Healthy Is Putting Attention Always', 'answer_3' => 'Health Insurance Portability and Accountability Act', 'answer_4' => 'Highly Intelligent Professional All American', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 127, 'lesson_id' => 13, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'The three key elements of terrorism are:', 'answer_1' => 'Violence, Fear, Intimidation', 'answer_2' => 'Peace, Harmony, Love', 'answer_3' => 'Diplomacy, Government, Environment', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 128, 'lesson_id' => 13, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'Terrorists have motivation in one of five goals; political, religious, environmental, racial and special interest.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 129, 'lesson_id' => 13, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'Terrorists are not an issue for Security Officers and Security Officers should never be concerned with any current events or threats.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 130, 'lesson_id' => 13, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'Which are the types of attacks used by terrorists:', 'answer_1' => 'Bombings', 'answer_2' => 'Suicide attacks', 'answer_3' => 'Kidnapping', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 131, 'lesson_id' => 13, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'This target involves little risk and a high probability of success.', 'answer_1' => 'Hard', 'answer_2' => 'Soft', 'answer_3' => 'Complicated', 'answer_4' => 'None of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 132, 'lesson_id' => 13, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'Counterintelligence (CI) refers to efforts made by intelligence organizations to prevent hostile or enemy intelligence organizations from successfully gathering and collecting intelligence against them.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 133, 'lesson_id' => 13, 'eq_spec_id' => null, 'correct' => 3, 'question' => 'Security Officers should always be __ of any terrorist threats or alerts.', 'answer_1' => 'Unaware', 'answer_2' => 'Ignorant', 'answer_3' => 'Knowledgeable and informed', 'answer_4' => 'None of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 134, 'lesson_id' => 13, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'Soft targets are defined as being:', 'answer_1' => 'Predictable', 'answer_2' => 'Unarmed', 'answer_3' => 'Having set routines', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 135, 'lesson_id' => 13, 'eq_spec_id' => null, 'correct' => 3, 'question' => 'One of the best ways to establish yourself as a hard target is to avoid forming __ in your daily life.', 'answer_1' => 'Bad habits', 'answer_2' => 'Fears', 'answer_3' => 'Routines', 'answer_4' => 'Panic', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 136, 'lesson_id' => 13, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'The most common types of terrorism attacks can be remembered by using the acronym:', 'answer_1' => 'CBRNE', 'answer_2' => 'MOLLE', 'answer_3' => 'OPORD', 'answer_4' => 'SCUBA', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 137, 'lesson_id' => 13, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'Most Terrorist attacks go through a planning process that involve pre-planning, surveillance, preparation and execution.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 138, 'lesson_id' => 14, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'Guards at an entrance, identification of individuals, controlling of movement of personnel and materials in and out of a facility that are essential to non-normal operations, and prevent unauthorized entry and exit are examples of:', 'answer_1' => 'Patrolling', 'answer_2' => 'Access control', 'answer_3' => 'Deadly force', 'answer_4' => 'None of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 139, 'lesson_id' => 14, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'As a Security Officer, if your gate is congested or backed up you are not required to check IDs to help speed up the flow of traffic.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 140, 'lesson_id' => 14, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'If an individual in the visitor access lane requests access to your property and they cannot produce valid identification you must:', 'answer_1' => 'Just let them on to the property if they have a good excuse', 'answer_2' => 'Follow your agencies standard operating procedures or post orders', 'answer_3' => 'Yell at them for forgetting their ID', 'answer_4' => 'Tell them to go away and never come back', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 141, 'lesson_id' => 14, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'If you, as a Security Officer working at an access control guard post of a gated community, let someone onto the property who was not supposed to be granted access, you will be held responsible for allowing that individual onto the property.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 142, 'lesson_id' => 15, 'eq_spec_id' => null, 'correct' => 3, 'question' => 'Identify Physical Security\'s three layers of protection.', 'answer_1' => 'Legislative, Executive, Judicial', 'answer_2' => 'Too cold, Too hot, Just Right', 'answer_3' => 'The Perimeter, Exterior of Buildings, Interior Controls', 'answer_4' => 'None of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 143, 'lesson_id' => 15, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'CPTED stands for Crime Prevention through Environmental Design.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 144, 'lesson_id' => 15, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'For someone to commit a crime, the following must be present:', 'answer_1' => 'Opportunity, Motive, Ability', 'answer_2' => 'Crowbar, Mask, Lock Picking Tools', 'answer_3' => 'Stop, Drop, Roll', 'answer_4' => 'Flashlight, Knife, Ski Mask', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 145, 'lesson_id' => 15, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'The goal of a perimeter protection system is to make it difficult for an intruder to enter and to detect an intruder if they make entry.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 146, 'lesson_id' => 16, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'A casual crowd (a crowd at the mall) has no unity of leadership.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 147, 'lesson_id' => 16, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'This type of crowd can easily become a mob:', 'answer_1' => 'Expressive', 'answer_2' => 'Aggressive', 'answer_3' => 'Casual', 'answer_4' => 'Cohesive', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 148, 'lesson_id' => 16, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'Most crowds a Security Officer will encounter are:', 'answer_1' => 'Concerts', 'answer_2' => 'Sporting events', 'answer_3' => 'Malls', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 149, 'lesson_id' => 16, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'When Security Officers are working at a site that involves a large crowd, the professional Security Officer should do which of the following?', 'answer_1' => 'Do not get into verbal confrontations with individuals in the crowd', 'answer_2' => 'Give calm and reasonable commands', 'answer_3' => 'Maintain self-control and self-discipline', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 150, 'lesson_id' => 17, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'Which type of weapons can be used against security officers.', 'answer_1' => 'Collapsible baton', 'answer_2' => 'Firearms or knives', 'answer_3' => 'OC or Pepper spray', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 151, 'lesson_id' => 17, 'eq_spec_id' => null, 'correct' => 2, 'question' => '#1: Treat every firearm as if it were loaded, even if you know it is unloaded. #2: Never point your firearm at anyone or anything you don\'t intend to shoot. #3: Trigger Finger Placement, keep your finger off the trigger until your sights are on target. #4: Know your target, what is surrounding your target and what is beyond your target are known as what 4 Rules?:', 'answer_1' => 'Tactics', 'answer_2' => 'The Four Firearm Safety Rules', 'answer_3' => 'Fundamentals of Marksmanship', 'answer_4' => 'Standard of Care', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 152, 'lesson_id' => 17, 'eq_spec_id' => 1, 'correct' => 2, 'question' => 'You can carry a firearm on duty as long as you have a Concealed Carry Weapons (CCW) Permit.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 153, 'lesson_id' => 17, 'eq_spec_id' => 1, 'correct' => 1, 'question' => 'An unarmed Security Officer may only carry weapons, excluding firearms, only if authorized by their agency and only if they are properly trained and have the proper certification for that weapon.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 154, 'lesson_id' => 18, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'During the course of a security officer\'s duties they may be confronted with people that may be suffering with:', 'answer_1' => 'Mental illness', 'answer_2' => 'Drug addiction', 'answer_3' => 'Disabilities', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 155, 'lesson_id' => 18, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'Special considerations should be taken by security officers when dealing with juveniles.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 156, 'lesson_id' => 18, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'Workplace violence situations normally occur as a result of:', 'answer_1' => 'One workers aggression towards his or her fellow employees', 'answer_2' => 'Domestic violence', 'answer_3' => 'Criminal activity involving personal injury to a worker', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 157, 'lesson_id' => 18, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'The key to dealing with the potential for workplace violence is:', 'answer_1' => 'Early intervention and addressing the issue', 'answer_2' => 'More medication', 'answer_3' => 'Removing the employee', 'answer_4' => 'None of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 158, 'lesson_id' => 18, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'All are types of workplace substance abuse except:', 'answer_1' => 'Depressants', 'answer_2' => 'Alcohol', 'answer_3' => 'Cocaine', 'answer_4' => 'Cigarettes', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 159, 'lesson_id' => 18, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'Never exceed your level of training and protection.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 160, 'lesson_id' => 18, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'Hazard Class 1 is', 'answer_1' => 'Explosives', 'answer_2' => 'Gasses', 'answer_3' => 'Radioactive material', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
        ];

        foreach ($examQuestions4 as $question) {
            DB::table('exam_questions')->insert($question);
        }

        // Final questions batch 5 (161-220) - Workplace Violence, Armed Security, and Firearms
        $examQuestions5 = [
            ['id' => 161, 'lesson_id' => 18, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'Public safety responders have a "Duty to Act"', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 162, 'lesson_id' => 18, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'Flammable gases are classified as Hazard Class 2.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 163, 'lesson_id' => 18, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'Hate crimes, robberies, and random shootings may be examples of:', 'answer_1' => 'Workplace violence', 'answer_2' => 'Substance abuse', 'answer_3' => 'Misdemeanors', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 164, 'lesson_id' => 18, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'Which of the following is not an example of warning signs in a distressed worker?', 'answer_1' => 'Aggressive attitude or comments', 'answer_2' => 'Sudden behavior changes or extreme behavior', 'answer_3' => 'Problem with authority figures and constant arguing', 'answer_4' => 'Always positive, kind, and polite', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 165, 'lesson_id' => 18, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'If there is a violent situation with a worker, you should handle it by yourself.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 166, 'lesson_id' => 18, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'An incident report should be done for any situation that involves drugs.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 167, 'lesson_id' => 18, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'If someone needs to be escorted from the facility who is acting or has the potential for violence, be sure to:', 'answer_1' => 'Wait for back up to arrive', 'answer_2' => 'Inform your supervisor and/or the police', 'answer_3' => 'Use extreme caution', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 168, 'lesson_id' => 18, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'When searching personnel and baggage. You should do which of the following if you discover narcotics:', 'answer_1' => 'Limit your exposure to the substance, use nitrile gloves when handling and photograph if possible.', 'answer_2' => 'Don\'t touch it; leave it alone (this becomes law enforcement\'s job at the next site, it\'s not your problem).', 'answer_3' => 'Contact 911 / law enforcement and your Supervisor and make sure you write a proper incident report.', 'answer_4' => 'Both A and C', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 169, 'lesson_id' => 18, 'eq_spec_id' => 1, 'correct' => 4, 'question' => 'If you believe that you have information on gang activity that would be helpful to authorities, you are encouraged to do one of the following:', 'answer_1' => 'Call 911 for life threatening emergencies', 'answer_2' => 'Report the incident to local law enforcement', 'answer_3' => 'Call "if you see something, say something" at 1-855-FLA-SAFE', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 170, 'lesson_id' => 18, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'Active Shooter is defined as an individual(s) actively attempting to or killing people in a populated area.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 171, 'lesson_id' => 19, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'A "G" license holder must have express written authority from his or her employer to carry a firearm while traveling to or from an armed security post.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 172, 'lesson_id' => 19, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'Once qualified pursuant to 28-hours of initial firearms training or a 4-hour (re)qualification course, a licensee may carry any type or caliber of firearm he or she wishes to carry.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 173, 'lesson_id' => 19, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'A Class "G" licensee is not required to carry an agency issued identification card at all times when performing regulated duties.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 174, 'lesson_id' => 19, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'A Class "G" licensee may carry more than 2 firearms when performing regulated duties.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 175, 'lesson_id' => 19, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'A person who knowingly possesses, issues, causes to be issued, sells, submits, or offers a fraudulent training certificate, proficiency form, or other official document that declares an applicant to have successfully completed any course of training required for licensure under chapter 493, commits a felony of the 3rd degree.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 176, 'lesson_id' => 20, 'eq_spec_id' => null, 'correct' => 3, 'question' => 'The type of liability that may include incarceration, probation, and monetary fines is:', 'answer_1' => 'Civil Liability', 'answer_2' => 'Negligent Liability', 'answer_3' => 'Criminal Liability', 'answer_4' => 'Administrative Liability', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 177, 'lesson_id' => 20, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'An agency head or supervisor who is responsible for equipping licensees with firearms might be liable under this legal theory if he or she knew, or should have known, that a licensee was incompetent, but nevertheless provided the licensee with a firearm.', 'answer_1' => 'Negligent Assignment', 'answer_2' => 'Negligent Entrustment', 'answer_3' => 'Excessive Use', 'answer_4' => 'Standard of Care', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 178, 'lesson_id' => 20, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'The recognized and accepted operating procedure, principle, or practice for an occupation or profession is called:', 'answer_1' => 'Standard Operating Procedures', 'answer_2' => 'Code of Conduct', 'answer_3' => 'Division of Licensing', 'answer_4' => 'Standard of Care', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 179, 'lesson_id' => 20, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'Liability occurs when a licensee fails to conduct him or herself within the standard of care for a security officer or private investigator, and that failure was the direct and proximate cause of an injury suffered.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 180, 'lesson_id' => 20, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'Battery occurs when a person actually and intentionally touches or strikes another person against the will of the other, or intentionally causes bodily harm to another.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 181, 'lesson_id' => 20, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'An armed officer can perform tasks during duty hours (such as refueling an agency-owned vehicle, purchasing carry-out food or beverage, or taking a restroom break) provided that such activities are carried out within a five-mile radius of the licensee\'s assigned duty post.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 182, 'lesson_id' => 21, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'A person is justified to use deadly force when he or she reasonably believes that such conduct is necessary for defense against another\'s use of unlawful force that is not life threatening.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 183, 'lesson_id' => 21, 'eq_spec_id' => null, 'correct' => 1, 'question' => '"Deadly Force" means force which a reasonable person would consider likely to cause death or serious bodily harm.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 184, 'lesson_id' => 21, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'A "warning shot" is only allowable if the circumstances that would otherwise warrant the use of deadly force are present.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 185, 'lesson_id' => 22, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'Always treat every firearm as if it were loaded.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 186, 'lesson_id' => 22, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'The muzzle of a firearm should always be pointed in a safe direction.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 187, 'lesson_id' => 22, 'eq_spec_id' => null, 'correct' => 3, 'question' => 'Never __ a firearm at anyone or anything that you do not intend to shoot.', 'answer_1' => 'Shove', 'answer_2' => 'Push', 'answer_3' => 'Point', 'answer_4' => 'None of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 188, 'lesson_id' => 22, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'While on the firing range, always keep the firearm __ and in its __ unless otherwise instructed.', 'answer_1' => 'unloaded, locker', 'answer_2' => 'secured, holster', 'answer_3' => 'cocked, in shooter\'s hand', 'answer_4' => 'None of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 189, 'lesson_id' => 22, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'Before training, the range instructor will inspect all firearms for proper function.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 190, 'lesson_id' => 22, 'eq_spec_id' => null, 'correct' => 3, 'question' => 'Never __ a firearm behind the firing line.', 'answer_1' => 'Cock', 'answer_2' => 'Fire', 'answer_3' => 'Unholster', 'answer_4' => 'Unload', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 191, 'lesson_id' => 22, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'Stop __ immediately at the cease fire command.', 'answer_1' => 'Eating', 'answer_2' => 'Talking', 'answer_3' => 'Smoking', 'answer_4' => 'Firing', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 192, 'lesson_id' => 22, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'If a weapon fails to fire, immediately leave the firing line with it and find the instructor.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 193, 'lesson_id' => 22, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'Eating and / or the use of tobacco products are permissible while on the firing line.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 194, 'lesson_id' => 22, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'It is not necessary to visually and physically inspect the cylinder of a revolver before handing it to another person.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 195, 'lesson_id' => 23, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'When loading a revolver, live rounds are placed into the open __.', 'answer_1' => 'Magazine', 'answer_2' => 'Cylinder', 'answer_3' => 'Trigger guard', 'answer_4' => 'Barrell', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 196, 'lesson_id' => 23, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'In a semi-automatic pistol, the magazine holds the __.', 'answer_1' => 'Rear sight', 'answer_2' => 'Trigger safety', 'answer_3' => 'Slide stop lever', 'answer_4' => 'Ammunition', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 197, 'lesson_id' => 24, 'eq_spec_id' => null, 'correct' => 3, 'question' => 'As it pertains to breath control, the best time to fire a shot is __.', 'answer_1' => 'While running after a suspect', 'answer_2' => 'As you inhale and exhale rapidly', 'answer_3' => 'The extended pause between breaths', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 198, 'lesson_id' => 24, 'eq_spec_id' => null, 'correct' => 1, 'question' => '__ __ is the relationship between the eye, front sight, rear sight and the target.', 'answer_1' => 'Sight picture', 'answer_2' => 'Proper stance', 'answer_3' => 'Sight alignment', 'answer_4' => 'Dominant eye', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 199, 'lesson_id' => 24, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'Improper trigger control causes more misses than any other action in the firing process.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 200, 'lesson_id' => 24, 'eq_spec_id' => null, 'correct' => 1, 'question' => '"Follow-through" involves maintaining sight alignment before, during and after firing a round.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 201, 'lesson_id' => 24, 'eq_spec_id' => null, 'correct' => 3, 'question' => 'A __ is the posture a shooter assumes while firing a shot.', 'answer_1' => 'Reach', 'answer_2' => 'Hug', 'answer_3' => 'Stance', 'answer_4' => 'Posture', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 202, 'lesson_id' => 24, 'eq_spec_id' => null, 'correct' => 3, 'question' => 'When firing from an Isosceles Stance your head and shoulders should be __ to the target.', 'answer_1' => 'Angled away from', 'answer_2' => 'Parallel', 'answer_3' => 'Square', 'answer_4' => 'None of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 203, 'lesson_id' => 24, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'When firing from the Weaver Stance, your weapon-side foot is to the rear.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 204, 'lesson_id' => 25, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'Semi-automatic pistols may operate differently based upon who manufactured them.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 205, 'lesson_id' => 25, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'A semi-automatic pistol functions by using the energy from the recoil of a single round of ammunition to extract and eject a fired cartridge from the pistol\'s chamber and load an unfired round from a magazine into the chamber for the next shot.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 206, 'lesson_id' => 25, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'The __ is the portion of the cartridge that becomes a projectile when in flight.', 'answer_1' => 'Wad', 'answer_2' => 'Magazine', 'answer_3' => 'Case', 'answer_4' => 'Bullet', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 207, 'lesson_id' => 26, 'eq_spec_id' => null, 'correct' => 3, 'question' => 'A __ occurs when the trigger is pulled, but the round fails to detonate.', 'answer_1' => 'Failure to eject', 'answer_2' => 'Double feed', 'answer_3' => 'Failure to fire', 'answer_4' => 'Failure to feed', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 208, 'lesson_id' => 27, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'Which of the following can be used as ammunition in a semi-automatic pistol?', 'answer_1' => 'Glaser-type', 'answer_2' => 'Teflon Coated', 'answer_3' => 'Armor Piercing', 'answer_4' => 'Full Metal Jacket', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 209, 'lesson_id' => 27, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'Armor piercing ammunition may be used by anyone within the State of Florida.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 210, 'lesson_id' => 27, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'In shotgun ammunition, the __ is the only part not found in any other centerfire cartridge.', 'answer_1' => 'Bullet', 'answer_2' => 'Casing', 'answer_3' => 'Primer', 'answer_4' => 'Wad', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 211, 'lesson_id' => 27, 'eq_spec_id' => null, 'correct' => 3, 'question' => '__ is the propellant used in most firearms.', 'answer_1' => 'Primer', 'answer_2' => 'Casings', 'answer_3' => 'Powder', 'answer_4' => 'None of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 212, 'lesson_id' => 27, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'The "duty life" and "shelf life" of ammunition are one and the same.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 213, 'lesson_id' => 27, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'Reloaded cartridges should be used for duty ammunition.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 214, 'lesson_id' => 28, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'A barricade position is defined as a position that is behind cover.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 215, 'lesson_id' => 28, 'eq_spec_id' => null, 'correct' => 4, 'question' => 'An example of cover is:', 'answer_1' => 'A fire hydrant', 'answer_2' => 'A vehicle engine block', 'answer_3' => 'Solid concrete wall', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 216, 'lesson_id' => 29, 'eq_spec_id' => null, 'correct' => 3, 'question' => 'When a subject is three to four feet away, one should employ the __ stance.', 'answer_1' => 'Isosceles', 'answer_2' => 'Weaver', 'answer_3' => 'Hip Shooting', 'answer_4' => 'Kneeling', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 217, 'lesson_id' => 29, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'One handed shooting capabilities are not a necessity.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 218, 'lesson_id' => 29, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'Point shooting is the technique used when you cannot use the sights on your weapon or you have no time to align the sights properly.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 219, 'lesson_id' => 30, 'eq_spec_id' => null, 'correct' => 2, 'question' => 'A firearm should be __ each time it is fired and fully inspected once per week.', 'answer_1' => 'Refinished', 'answer_2' => 'Cleaned', 'answer_3' => 'Sold', 'answer_4' => 'All of the above', 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
            ['id' => 220, 'lesson_id' => 31, 'eq_spec_id' => null, 'correct' => 1, 'question' => 'When drawing a handgun from the holster, it is important to keep your finger outside of the trigger guard and off of the trigger.', 'answer_1' => 'True', 'answer_2' => 'False', 'answer_3' => null, 'answer_4' => null, 'answer_5' => null, 'deact_at' => null, 'deact_by' => null],
        ];

        foreach ($examQuestions5 as $question) {
            DB::table('exam_questions')->insert($question);
        }

        // Set the sequence to continue from 220
        DB::statement("SELECT setval('exam_questions_id_seq', 220, true);");
    }
}
