{{-- Course Schedules Panel --}}
<div class="frost-secondary-bg py-5">
    <div class="container">
        <div class="row mb-5">
            <div class="col-12 text-center">
                <h2 class="text-white">Course Schedules</h2>
                <h5 class="text-white-50">View available dates for our security training courses</h5>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-3 col-md-4">
                <div class="schedule-sidebar">
                    <h5 class="text-white mb-4">Course Types</h5>
                    <div class="course-filter-buttons">
                        <button class="btn btn-outline-light btn-sm mb-2 w-100 active" data-course="all">All Courses</button>
                        <button class="btn btn-outline-light btn-sm mb-2 w-100" data-course="d40">Class D (Armed) - D40</button>
                        <button class="btn btn-outline-light btn-sm mb-2 w-100" data-course="g28">Class G (Unarmed) - G28</button>
                    </div>
                </div>
            </div>

            <div class="col-lg-9 col-md-8">
                <div class="schedule-calendar">
                    <div class="calendar-header d-flex justify-content-between align-items-center mb-4">
                        <h4 class="text-white mb-0" id="currentMonth">August 2025</h4>
                        <div class="calendar-nav">
                            <button class="btn btn-outline-light btn-sm me-2" id="prevMonth">
                                <i class="fas fa-chevron-left"></i>
                            </button>
                            <button class="btn btn-primary btn-sm me-2" id="todayBtn">Today</button>
                            <button class="btn btn-outline-light btn-sm" id="nextMonth">
                                <i class="fas fa-chevron-right"></i>
                            </button>
                        </div>
                    </div>

                    <div class="calendar calendar-grid" id="calendarGrid">
                        <!-- Calendar will be generated by JavaScript -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
.calendar-grid {
    background: rgb(0, 63, 82) !important;
    border-radius: 8px;
    overflow: hidden;
    box-shadow: 0 4px 16px rgba(0, 0, 0, 0.1);
}

.calendar-header-row {
    background: var(--primary-800);
    color: white;
    font-weight: 600;
}

.calendar-header-row .calendar-day {
    padding: 15px;
    text-align: center;
    border-right: 1px solid var(--primary-600);
}

.calendar-week {
    display: flex;
    border-bottom: 1px solid #e9ecef;
}

.calendar-day {
    flex: 1;
    min-height: 120px;
    padding: 8px;
    border-right: 1px solid #e9ecef;
    background: rgba(255,255,255, 0.1);
    position: relative;
}

.calendar-day:last-child {
    border-right: none;
}

.calendar-day.other-month {
    background: #5f5f5f;
    color: #131516;
}

.calendar-day.today {
    background: #fff3cd;
    border: 2px solid var(--accent-theme);
}

.day-number {
    font-weight: 600;
    margin-bottom: 4px;
    font-size: 14px;
}

.course-event {
    background: var(--accent-theme);
    color: white;
    padding: 2px 6px;
    border-radius: 4px;
    font-size: 10px;
    margin-bottom: 2px;
    display: block;
    text-decoration: none;
    font-weight: 600;
}

.course-event:hover {
    background: var(--highlight-theme);
    color: white;
    text-decoration: none;
}

.course-event.d40 {
    background: #2563eb;
}

.course-event.g28 {
    background: #7c3aed;
}

.schedule-sidebar {
    background: var(--primary-700);
    padding: 20px;
    border-radius: 8px;
    margin-bottom: 20px;
}

.course-filter-buttons .btn.active {
    background: var(--accent-theme);
    border-color: var(--accent-theme);
}
</style>

<script>
// Course schedule data
const courseSchedules = [
    // August 2025 Class D (Armed Security) - D40
    { date: '2025-08-01', course: 'd40', title: 'Florida D40 D', type: 'Class D Armed' },
    { date: '2025-08-04', course: 'd40', title: 'Florida D40 D', type: 'Class D Armed' },
    { date: '2025-08-05', course: 'd40', title: 'Florida D40 D', type: 'Class D Armed' },
    { date: '2025-08-06', course: 'd40', title: 'Florida D40 D', type: 'Class D Armed' },
    { date: '2025-08-07', course: 'd40', title: 'Florida D40 D', type: 'Class D Armed' },
    { date: '2025-08-08', course: 'd40', title: 'Florida D40 D', type: 'Class D Armed' },

    { date: '2025-08-11', course: 'd40', title: 'Florida D40 D', type: 'Class D Armed' },
    { date: '2025-08-12', course: 'd40', title: 'Florida D40 D', type: 'Class D Armed' },
    { date: '2025-08-13', course: 'd40', title: 'Florida D40 D', type: 'Class D Armed' },
    { date: '2025-08-14', course: 'd40', title: 'Florida D40 D', type: 'Class D Armed' },
    { date: '2025-08-15', course: 'd40', title: 'Florida D40 D', type: 'Class D Armed' },

    { date: '2025-08-18', course: 'd40', title: 'Florida D40 D', type: 'Class D Armed' },
    { date: '2025-08-19', course: 'd40', title: 'Florida D40 D', type: 'Class D Armed' },
    { date: '2025-08-20', course: 'd40', title: 'Florida D40 D', type: 'Class D Armed' },
    { date: '2025-08-21', course: 'd40', title: 'Florida D40 D', type: 'Class D Armed' },
    { date: '2025-08-22', course: 'd40', title: 'Florida D40 D', type: 'Class D Armed' },

    { date: '2025-08-25', course: 'd40', title: 'Florida D40 D', type: 'Class D Armed' },
    { date: '2025-08-26', course: 'd40', title: 'Florida D40 D', type: 'Class D Armed' },
    { date: '2025-08-27', course: 'd40', title: 'Florida D40 D', type: 'Class D Armed' },
    { date: '2025-08-28', course: 'd40', title: 'Florida D40 D', type: 'Class D Armed' },
    { date: '2025-08-29', course: 'd40', title: 'Florida D40 D', type: 'Class D Armed' },

    // Class G (Unarmed Security) - G28
    { date: '2025-08-04', course: 'g28', title: 'Florida G28 G', type: 'Class G Unarmed' },
    { date: '2025-08-05', course: 'g28', title: 'Florida G28 G', type: 'Class G Unarmed' },
    { date: '2025-08-06', course: 'g28', title: 'Florida G28 G', type: 'Class G Unarmed' },

    { date: '2025-08-18', course: 'g28', title: 'Florida G28 G', type: 'Class G Unarmed' },
    { date: '2025-08-19', course: 'g28', title: 'Florida G28 G', type: 'Class G Unarmed' },
    { date: '2025-08-20', course: 'g28', title: 'Florida G28 G', type: 'Class G Unarmed' },
];

let currentDate = new Date(2025, 7, 1); // August 2025
let activeFilter = 'all';

function generateCalendar(year, month) {
    const firstDay = new Date(year, month, 1);
    const lastDay = new Date(year, month + 1, 0);
    const startDate = new Date(firstDay);
    const endDate = new Date(lastDay);

    // Start from Sunday of the first week
    startDate.setDate(startDate.getDate() - startDate.getDay());
    // End on Saturday of the last week
    endDate.setDate(endDate.getDate() + (6 - endDate.getDay()));

    const calendarGrid = document.getElementById('calendarGrid');
    const currentMonth = document.getElementById('currentMonth');

    // Update month header
    currentMonth.textContent = firstDay.toLocaleDateString('en-US', { month: 'long', year: 'numeric' });

    // Clear calendar
    calendarGrid.innerHTML = '';

    // Add header row
    const headerRow = document.createElement('div');
    headerRow.className = 'calendar-header-row d-flex';
    ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].forEach(day => {
        const dayHeader = document.createElement('div');
        dayHeader.className = 'calendar-day';
        dayHeader.textContent = day;
        headerRow.appendChild(dayHeader);
    });
    calendarGrid.appendChild(headerRow);

    // Generate calendar weeks
    let currentWeekDate = new Date(startDate);
    const today = new Date();

    while (currentWeekDate <= endDate) {
        const weekRow = document.createElement('div');
        weekRow.className = 'calendar-week';

        for (let i = 0; i < 7; i++) {
            const dayCell = document.createElement('div');
            dayCell.className = 'calendar-day';

            const dayNumber = document.createElement('div');
            dayNumber.className = 'day-number';
            dayNumber.textContent = currentWeekDate.getDate();

            // Check if it's outside current month
            if (currentWeekDate.getMonth() !== month) {
                dayCell.classList.add('other-month');
            }

            // Check if it's today
            if (currentWeekDate.toDateString() === today.toDateString()) {
                dayCell.classList.add('today');
            }

            dayCell.appendChild(dayNumber);

            // Add course events for this day
            const dayString = currentWeekDate.toISOString().split('T')[0];
            const dayEvents = courseSchedules.filter(event => {
                if (activeFilter === 'all') return event.date === dayString;
                return event.date === dayString && event.course === activeFilter;
            });

            dayEvents.forEach(event => {
                const eventElement = document.createElement('a');
                eventElement.className = `course-event ${event.course}`;
                eventElement.textContent = event.title;
                eventElement.href = '#';
                dayCell.appendChild(eventElement);
            });

            weekRow.appendChild(dayCell);
            currentWeekDate.setDate(currentWeekDate.getDate() + 1);
        }

        calendarGrid.appendChild(weekRow);
    }
}

// Initialize calendar
document.addEventListener('DOMContentLoaded', function() {
    generateCalendar(currentDate.getFullYear(), currentDate.getMonth());

    // Navigation buttons
    document.getElementById('prevMonth').addEventListener('click', function() {
        currentDate.setMonth(currentDate.getMonth() - 1);
        generateCalendar(currentDate.getFullYear(), currentDate.getMonth());
    });

    document.getElementById('nextMonth').addEventListener('click', function() {
        currentDate.setMonth(currentDate.getMonth() + 1);
        generateCalendar(currentDate.getFullYear(), currentDate.getMonth());
    });

    document.getElementById('todayBtn').addEventListener('click', function() {
        currentDate = new Date();
        generateCalendar(currentDate.getFullYear(), currentDate.getMonth());
    });

    // Filter buttons
    document.querySelectorAll('[data-course]').forEach(button => {
        button.addEventListener('click', function() {
            // Remove active class from all buttons
            document.querySelectorAll('[data-course]').forEach(btn => btn.classList.remove('active'));
            // Add active class to clicked button
            this.classList.add('active');

            activeFilter = this.dataset.course;
            generateCalendar(currentDate.getFullYear(), currentDate.getMonth());
        });
    });
});
</script>
