<!-- AdminLTE Card Header with Tabs -->
<div class="card-header p-0 border-bottom-0">
    <!-- Card Title -->
    <div class="d-flex justify-content-between align-items-center p-3 border-bottom">
        <h3 class="card-title mb-0">
            <i class="fas fa-cloud mr-2 text-primary"></i>
            <span class="text-primary font-weight-bold">Media Manager</span>
        </h3>
        <div class="d-flex align-items-center">
            <span class="badge badge-primary px-3 py-2 mr-2">
                <i class="fas fa-database mr-1"></i>
                <span id="currentDiskDisplay">Public</span> Storage
            </span>
            <div id="loadingIndicator" class="badge badge-secondary px-3 py-2 d-none">
                <i class="fas fa-spinner fa-spin mr-1"></i>Loading...
            </div>
        </div>
    </div>

    <!-- Storage Type Tabs -->
    <ul class="nav nav-tabs media-tabs" role="tablist">
        <!-- Public Tab -->
        <li class="nav-item">
            <a class="nav-link active" href="#public" data-disk="public" role="tab">
                <i class="fas fa-globe mr-2"></i>Public
                <small class="d-block">Images, Assets</small>
                <span class="disk-status-indicator" data-disk="public"></span>
            </a>
        </li>

        <!-- Private Tab -->
        @if(auth('admin')->check() && auth('admin')->user()->IsInstructor())
        <li class="nav-item">
            <a class="nav-link" href="#private" data-disk="local" role="tab">
                <i class="fas fa-shield-alt mr-2"></i>Private
                <small class="d-block">Documents, Files</small>
                <span class="disk-status-indicator" data-disk="local"></span>
            </a>
        </li>
        @endif

        <!-- Archive S3 Tab -->
        @if(auth('admin')->check() && auth('admin')->user()->IsAdministrator())
        <li class="nav-item">
            <a class="nav-link" href="#s3" data-disk="s3" role="tab">
                <i class="fas fa-archive mr-2"></i>Archive S3
                <small class="d-block">Long-term Storage</small>
                <span class="disk-status-indicator" data-disk="s3"></span>
            </a>
        </li>
        @endif
    </ul>

    <!-- Access Level Indicator -->
    <div class="p-3 border-top">
        <div class="d-flex justify-content-between align-items-center">
            <div>
                <small class="text-muted">
                    <i class="fas fa-user-shield mr-1"></i>
                    Access Level:
                    @if(auth('admin')->check())
                        @php $user = auth('admin')->user(); @endphp
                        @if($user->IsSysAdmin())
                            <span class="text-success font-weight-bold">System Admin</span> - Full access to all storage locations
                        @elseif($user->IsAdministrator())
                            <span class="text-success font-weight-bold">Admin</span> - Full access to all storage locations
                        @elseif($user->IsSupport())
                            <span class="text-info font-weight-bold">Support</span> - Admin access, including private storage
                        @elseif($user->IsInstructor())
                            <span class="text-warning font-weight-bold">Instructor</span> - Admin access, including private storage
                        @else
                            <span class="text-secondary font-weight-bold">Student/Guest</span> - Public read-only access
                        @endif
                    @else
                        <span class="text-muted">Not authenticated</span>
                    @endif
                </small>

                <!-- Media Manager Breadcrumbs -->
                <div class="mt-2">
                    <nav aria-label="Media Manager breadcrumb">
                        <ol class="breadcrumb breadcrumb-sm mb-0" id="mediaBreadcrumb">
                            <!-- Breadcrumbs will be dynamically generated by JavaScript -->
                            <li class="breadcrumb-item">
                                <i class="fas fa-hdd mr-1 text-muted"></i>
                                <span id="currentDiskBreadcrumb" class="breadcrumb-link">Public Storage</span>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">
                                <i class="fas fa-folder mr-1 text-primary"></i>
                                <span>Media Root</span>
                            </li>
                        </ol>
                    </nav>
                </div>
            </div>

            <!-- File Management Tools -->
            <div class="file-management-tools d-flex justify-content-between align-items-center" id="headerFileManagement">
                <div class="btn-group" role="group">
                    <!-- Create Folder Button -->
                    <button type="button" class="btn btn-outline-primary btn-sm" id="createFolderBtn" title="Create New Folder">
                        <i class="fas fa-folder-plus"></i>
                    </button>

                    <!-- Upload File Button -->
                    <button type="button" class="btn btn-outline-success btn-sm" id="uploadFileBtn" title="Upload Files">
                        <i class="fas fa-upload"></i>
                    </button>

                    <!-- Refresh Button -->
                    <button type="button" class="btn btn-outline-info btn-sm" id="refreshBtn" title="Refresh Current View">
                        <i class="fas fa-sync-alt"></i>
                    </button>

                    <!-- Delete Selected Button (initially disabled) -->
                    <button type="button" class="btn btn-outline-danger btn-sm" id="deleteSelectedBtn" title="Delete Selected Files" disabled>
                        <i class="fas fa-trash"></i>
                    </button>
                </div>

                <!-- View Toggle Buttons -->
                <div class="btn-group" role="group" aria-label="View Toggle">
                    <button type="button" class="btn btn-outline-secondary btn-sm active" id="gridViewBtn" title="Grid View" data-view="grid">
                        <i class="fas fa-th-large"></i>
                    </button>
                    <button type="button" class="btn btn-outline-secondary btn-sm" id="listViewBtn" title="List View" data-view="list">
                        <i class="fas fa-list"></i>
                    </button>
                </div>
            </div>

                <!-- Hidden file input for general uploads -->
                <input type="file" id="generalFileInput" multiple style="display: none;">

                <!-- Progress Container -->
                <div class="mt-2" id="headerProgressContainer" style="display: none;">
                    <div class="progress" style="height: 4px;">
                        <div class="progress-bar progress-bar-striped progress-bar-animated" id="headerProgressBar" role="progressbar" style="width: 0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    <small class="text-muted" id="progressText">Uploading...</small>
                </div>
            </div>
        </div>
    </div>
</div>
